issue/FINI-508: Integrate linter errors into build and fix them
Lombiq/NPM-Targets pull request #2
Opened 2021-02-15 16:01 UTC by Luko6

FINI-508

2021-02-15 20:01 UTC, Piedone requested changes

2021-02-15 20:01 UTC, Piedone commented on Lombiq.Npm.Targets.targets
> +        Condition="$([System.Text.RegularExpressions.Regex]::IsMatch('$(PrebuildOutput)', 'error'))" />
Ha jól értem, akkor ha azt találjuk az outputban, hogy "error", akkor ezt iratjuk ki. De nem csak ESlint error lehet, hanem bármi, ennél specifikusabb kellene.

2021-02-15 20:01 UTC, Piedone commented on Lombiq.Npm.Targets.targets
> +        Condition="$([System.Text.RegularExpressions.Regex]::IsMatch('$(PrebuildOutput)', 'error'))" />
Ezt az egészet nem a Gulp Extensionsbe kellene inkább? Most lett a kettő között egy rejtettt dependency.

2021-02-16 15:30 UTC, Luko6 commented on Lombiq.Npm.Targets.targets
> +        Condition="$([System.Text.RegularExpressions.Regex]::IsMatch('$(PrebuildOutput)', 'error'))" />
Ezzel az a probléma, hogy az `npm run dotnet-prebuild --if-present` command az innen fut le, és az output itt fogható meg

2021-02-16 16:35 UTC, Piedone commented on Lombiq.Npm.Targets.targets
> +        Condition="$([System.Text.RegularExpressions.Regex]::IsMatch('$(PrebuildOutput)', 'error'))" />
Hmm, hát nem tudom hogyan lehet ezt megoldani, de ez így biztos nem lesz megfelelő. A GE-ből ha ez dependency, akkor nem lehet kiolvasni a `$(PrebuildOutput)`-ot? Ezek ilyen globális cuccok.

2021-02-19 14:31 UTC, Piedone approved these changes

2021-03-06 23:04 UTC, merged