OSOE-128: Fix markdown files.
Lombiq/NPM-Targets pull request #21
Opened 2022-07-21 15:04 UTC by DAud-IcI

OSOE-128

2022-07-21 22:14 UTC, Piedone requested changes

2022-07-21 22:14 UTC, Piedone commented on Readme.md
> +    * If you get _nvm: command not found_ error, reload your shell profile first (`source ~/.bashrc`) and try again.
`-` is easier to write for the bullet point and we use that everywhere.

2022-07-21 22:14 UTC, Piedone commented on Lombiq.Npm.Targets.targets
> -          IgnoreStandardErrorWarningFormat="true"
Why is this needed? Did you consult with Oliver?

2022-07-22 00:37 UTC, DAud-IcI commented on Lombiq.Npm.Targets.targets
> -          IgnoreStandardErrorWarningFormat="true"
It must be removed, so we can emit MSBuild warnings. Discussion with Oliver [here](https://teams.microsoft.com/l/message/19:0e3ad2d722c74eef93386ecfeb790963@thread.skype/1658256414396?tenantId=959ede5a-38e9-44e6-adc8-85553beb8220&groupId=00c48e7c-aebf-4247-84cf-bb7c31061ef1&parentMessageId=1657013971481&teamName=Open%20Source%20Orchard%20Extensions%20developers&channelName=General&createdTime=1658256414396).

2022-07-22 00:44 UTC, DAud-IcI commented on Readme.md
> +    * If you get _nvm: command not found_ error, reload your shell profile first (`source ~/.bashrc`) and try again.
We use both style very often, in fact `*` is used in this file.
This was an autofix as well. My guess is that the linter is trying to enforce consistent usage of bullet character within the document and just applies the first one it finds. In this case the [first one is an asterisk](https://github.com/Lombiq/NPM-Targets/blob/dev/Readme.md?plain=1#L62)  (link points to file dev branch).

2022-07-22 00:46 UTC, DAud-IcI commented on Readme.md
> +    * If you get _nvm: command not found_ error, reload your shell profile first (`source ~/.bashrc`) and try again.
Also, `*` is <kbd>AltGr</kbd>+<kbd>-</kbd>.
I agree that typing only <kbd>-</kbd> is easier,, but not by so much that we need to worry about it.

2022-07-22 07:59 UTC, 0liver commented on Readme.md
> +    * If you get _nvm: command not found_ error, reload your shell profile first (`source ~/.bashrc`) and try again.
Asterisks are prettier.

Hyphens are easier to type.

Two-dimensional optimization problem ahead. ⚠️ 

Once we agree on "the best" bullet point character, we can enforce it using [configuration](https://github.com/DavidAnson/markdownlint/blob/v0.26.0/doc/Rules.md#md004---unordered-list-style).

2022-07-22 12:10 UTC, Piedone commented on Lombiq.Npm.Targets.targets
> -          IgnoreStandardErrorWarningFormat="true"
OK then.

2022-07-22 12:11 UTC, Piedone commented on Readme.md
> +    * If you get _nvm: command not found_ error, reload your shell profile first (`source ~/.bashrc`) and try again.
This file using asterisk before is an exception, then, because we overwhelmingly use hyphen otherwise, please use that here too.

2022-07-22 22:23 UTC, DAud-IcI commented on Readme.md
> +    * If you get _nvm: command not found_ error, reload your shell profile first (`source ~/.bashrc`) and try again.
fwiw all of the license.md files use asterisk too.

2022-07-24 23:28 UTC, Piedone approved these changes

2022-07-27 12:47 UTC, 0liver approved these changes

2022-07-28 20:40 UTC, merged